### ISSUE TITLE
Make a 3D visualization of the projector setup

### ISSUE THREAD

**Issue by eigenvivek** [v715/DRRs.jl#4]
Visualization of #1 and #2 

Inspired by this https://makie.juliaplots.org/stable/documentation/backends/wglmakie/#record_a_statemap

**Comment by v715** [comment]
It looks like PlotlyJS will be better for this, it's more stable

- https://plotly.com/julia/3d-mesh/
- https://plotly.com/julia/reference/mesh3d/
